let File = require('../File');
let path = require('path');

class MockEntryPlugin {
    /**
     * @param {import('../Pod')} pod
     */
    constructor(pod) {
        // TODO: Remove in Pod 7 -- Here for backwards compat if a plugin requires this file
        this.pod = pod || global.Pod;
    }

    /**
     * Handle the deletion of the temporary pod.js
     * output file that was generated by webpack.
     *
     * This file is created when the user hasn't
     * requested any JavaScript compilation, but
     * webpack still requires an entry.
     *
     * @param {import("webpack").Compiler} compiler
     */
    apply(compiler) {
        compiler.hooks.done.tap('MockEntryPlugin', stats => {
            const assets = stats.toJson().assets || [];
            const temporaryOutputFile = assets.find(asset => asset.name === 'pod.js');

            if (!temporaryOutputFile) {
                return;
            }

            delete stats.compilation.assets[temporaryOutputFile.name];

            File.find(
                path.resolve(this.pod.config.publicPath, temporaryOutputFile.name)
            ).delete();
        });
    }
}

module.exports = MockEntryPlugin;
